const names = [
    "Red / Blue / Yellow",
    "Gold / Silver / Crystal",
    "Ruby / Sapphire / Emerald",
    "FireRed / LeafGreen",
    "Diamond / Pearl / Platinum",
    "HeartGold / SoulSilver",
    "Black / White",
    "Black 2 / White 2",
    "X / Y",
    "OmegaRuby / AlphaSapphire",
    "Sun / Moon",
    "Ultra Sun / Ultra Moon",
    "Sword and Shield",
];

const routes = [
    //--Red / Blue / Yellow--//
    [
        "Starter",
        "Pallet Town",
        "Route 1",
        "Viridian City",
        "Route 22",
        "Route 2",
        "Viridian Forest",
        "Route 3",
        "Route 4",
        "Mt. Moon",
        "Cerulean City",
        "Route 24",
        "Route 25",
        "Route 5",
        "Route 6",
        "Vermillion City",
        "Route 11",
        "Diglett's Cave",
        "Route 9",
        "Route 10",
        "Rock Tunnel",
        "Pokémon Tower",
        "Route 12",
        "Route 8",
        "Route 7",
        "Celadon City",
        "Route 16",
        "Route 17",
        "Route 18",
        "Fuschia City",
        "Safari Zone",
        "Route 15",
        "Route 14",
        "Route 13",
        "Power Plant",
        "Route 19",
        "Route 20",
        "Seafoam Islands",
        "Cinnabar Island",
        "Pokémon Mansion",
        "Route 21",
        "Route 23",
        "Victory Road",
        "Cerulean Cave",
    ],
    //--Gold / Silver / Crystal--//
    [
        "Starter",
        "New Bark Town",
        "Route 29",
        "Cherrygrove City",
        "Route 30",
        "Route 31",
        "Dark Cave",
        "Violet City",
        "Sport Tower",
        "Route 32",
        "Ruins of Alph",
        "Union Cave",
        "Route 33",
        "Azalea Town",
        "Slowpoke Well",
        "Ilex Forest",
        "Route 34",
        "Goldenrod City",
        "Route 35",
        "National Park",
        "Route 36",
        "Route 37",
        "Ecruteak City",
        "Burned Tower",
        "Tin Tower",
        "Route 38",
        "Route 39",
        "Olivine City",
        "Route 40",
        "Route 41",
        "Whirl Islands",
        "Cianwood City",
        "Route 42",
        "Mt. Mortar",
        "Mahogany Town",
        "Rocket Hideout",
        "Route 43",
        "Lake of Rage",
        "Route 44",
        "Ice Path",
        "Blackthorn City",
        "Dragon's Den",
        "Route 45",
        "Dark Cave 2",
        "Route 46",
        "Route 27",
        "Tohjo Falls",
        "Route 26",
        "Victory Road",
        "Indigo Plateau",
        "Vermillion City",
        "Route 6",
        "Saffron City",
        "Route 5",
        "Route 7",
        "Route 8",
        "Route 10",
        "Rock Tunnel",
        "Route 9",
        "Cerulean City",
        "Route 24",
        "Route 25",
        "Route 4",
        "Route 16",
        "Route 17",
        "Route 18",
        "Fuschia City",
        "Route 15",
        "Route 14",
        "Route 13",
        "Route 12",
        "Route 11",
        "Diglett's Cave",
        "Route 2",
        "Pewter City",
        "Route 3",
        "Mt. Moon",
        "Viridian City",
        "Route 1",
        "Pallet Town",
        "Route 21",
        "Cinnabar Island",
        "Route 20",
        "Route 19",
        "Route 22",
        "Route 28",
        "Mt. Silver",
    ],
    //--Ruby / Sapphire / Emerald--//
    [
        "Starter",
        "Littleroot Town",
        "Route 101",
        "Route 102",
        "Route 103",
        "Petalburg City",
        "Route 104",
        "Petalburg Woods",
        "Rustboro City",
        "Route 115",
        "Route 116",
        "Rusturf Tunnel",
        "Dewford Town",
        "Route 106",
        "Granite Cave",
        "Route 107",
        "Slateport City",
        "Route 110",
        "Altering Cave",
        "New Mauville",
        "Route 117",
        "Route 111",
        "Mirage Tower (Emerald)",
        "Route 112",
        "Fiery Path",
        "Route 113",
        "Route 114",
        "Desert Underpass (Emerald)",
        "Meteor Falls",
        "Jagged Pass",
        "Lavaridge Town",
        "Route 118",
        "Route 119",
        "Fortree City",
        "Route 120",
        "Route 121",
        "Safari Zone",
        "Lilycove City",
        "Route 122",
        "Mt. Pyre",
        "Route 123",
        "Team Magma Hideout (Emerald)",
        "Route 124",
        "Mossdeep City",
        "Route 125",
        "Shoal Cave",
        "Route 127",
        "Route 128",
        "Seafloor Cavern",
        "Route 126",
        "Sootopolis City",
        "Cave of Origin",
        "Route 129",
        "Route 130",
        "Route 131",
        "Sky Pillar",
        "Pacifidlog Town",
        "Mirage Island",
        "Route 105",
        "Route 108",
        "Abandoned Ship",
        "Route 109",
        "Route 132",
        "Route 133",
        "Route 134",
        "Ever Grande City",
        "Victory Road",
        "S.S. Tidal",
        "Battle Frontier",
        "Artisan Cave",
    ],
    //--Diamond / Pearl / Platinum--//
    [],
    //--HeartGold / SoulSilver--//
    [],
    //--Black / White--//
    [],
    //--Black 2 / White 2--//
    [],
    //--X / Y--//
    [],
    //--OmegaRuby / AlphaSapphire--//
    [],
    //--Sun / Moon--//
    [],
    //--Ultra Sun / Ultra Moon--//
    [],
    //--Sword and Shield--//
    [],
];

export default {
    names,
    routes,
};
