const names = [
    "Red / Blue / Yellow",
    "Gold / Silver / Crystal",
    "Ruby / Sapphire / Emerald",
    "FireRed / LeafGreen",
    "Diamond / Pearl / Platinum",
    "HeartGold / SoulSilver",
    "Black / White",
    "Black 2 / White 2",
    "X / Y",
    "OmegaRuby / AlphaSapphire",
    "Sun / Moon",
    "Ultra Sun / Ultra Moon",
    "Sword and Shield",
];

const routes = [
    //--Red / Blue / Yellow--//
    [
        "Starter",
        "Pallet Town",
        "Route 1",
        "Viridian City",
        "Route 22",
        "Route 2",
        "Viridian Forest",
        "Route 3",
        "Route 4",
        "Mt. Moon",
        "Cerulean City",
        "Route 24",
        "Route 25",
        "Route 5",
        "Route 6",
        "Vermillion City",
        "Route 11",
        "Diglett's Cave",
        "Route 9",
        "Route 10",
        "Rock Tunnel",
        "Pokémon Tower",
        "Route 12",
        "Route 8",
        "Route 7",
        "Celadon City",
        "Route 16",
        "Route 17",
        "Route 18",
        "Fuschia City",
        "Safari Zone",
        "Route 15",
        "Route 14",
        "Route 13",
        "Power Plant",
        "Route 19",
        "Route 20",
        "Seafoam Islands",
        "Cinnabar Island",
        "Pokémon Mansion",
        "Route 21",
        "Route 23",
        "Victory Road",
        "Cerulean Cave",
    ],

    //--Gold / Silver / Crystal--//
    [
        "Starter",
        "New Bark Town",
        "Route 29",
        "Cherrygrove City",
        "Route 30",
        "Route 31",
        "Dark Cave",
        "Violet City",
        "Sprout Tower",
        "Route 32",
        "Ruins of Alph",
        "Union Cave",
        "Route 33",
        "Azalea Town",
        "Slowpoke Well",
        "Ilex Forest",
        "Route 34",
        "Goldenrod City",
        "Route 35",
        "National Park",
        "Route 36",
        "Route 37",
        "Ecruteak City",
        "Burned Tower",
        "Tin Tower",
        "Route 38",
        "Route 39",
        "Olivine City",
        "Route 40",
        "Route 41",
        "Whirl Islands",
        "Cianwood City",
        "Route 42",
        "Mt. Mortar",
        "Mahogany Town",
        "Rocket Hideout",
        "Route 43",
        "Lake of Rage",
        "Route 44",
        "Ice Path",
        "Blackthorn City",
        "Dragon's Den",
        "Route 45",
        "Dark Cave 2",
        "Route 46",
        "Route 27",
        "Tohjo Falls",
        "Route 26",
        "Victory Road",
        "Indigo Plateau",
        "Vermillion City",
        "Route 6",
        "Saffron City",
        "Route 5",
        "Route 7",
        "Route 8",
        "Route 10",
        "Rock Tunnel",
        "Route 9",
        "Cerulean City",
        "Route 24",
        "Route 25",
        "Route 4",
        "Route 16",
        "Route 17",
        "Route 18",
        "Fuschia City",
        "Route 15",
        "Route 14",
        "Route 13",
        "Route 12",
        "Route 11",
        "Diglett's Cave",
        "Route 2",
        "Pewter City",
        "Route 3",
        "Mt. Moon",
        "Viridian City",
        "Route 1",
        "Pallet Town",
        "Route 21",
        "Cinnabar Island",
        "Route 20",
        "Route 19",
        "Route 22",
        "Route 28",
        "Mt. Silver",
    ],

    //--Ruby / Sapphire / Emerald--//
    [
        "Starter",
        "Littleroot Town",
        "Route 101",
        "Route 102",
        "Route 103",
        "Petalburg City",
        "Route 104",
        "Petalburg Woods",
        "Rustboro City",
        "Route 115",
        "Route 116",
        "Rusturf Tunnel",
        "Dewford Town",
        "Route 106",
        "Granite Cave",
        "Route 107",
        "Slateport City",
        "Route 110",
        "Altering Cave",
        "New Mauville",
        "Route 117",
        "Route 111",
        "Mirage Tower (Emerald)",
        "Route 112",
        "Fiery Path",
        "Route 113",
        "Route 114",
        "Desert Underpass (Emerald)",
        "Meteor Falls",
        "Jagged Pass",
        "Lavaridge Town",
        "Route 118",
        "Route 119",
        "Fortree City",
        "Route 120",
        "Route 121",
        "Safari Zone",
        "Lilycove City",
        "Route 122",
        "Mt. Pyre",
        "Route 123",
        "Team Magma Hideout (Emerald)",
        "Route 124",
        "Mossdeep City",
        "Route 125",
        "Shoal Cave",
        "Route 127",
        "Route 128",
        "Seafloor Cavern",
        "Route 126",
        "Sootopolis City",
        "Cave of Origin",
        "Route 129",
        "Route 130",
        "Route 131",
        "Sky Pillar",
        "Pacifidlog Town",
        "Mirage Island",
        "Route 105",
        "Route 108",
        "Abandoned Ship",
        "Route 109",
        "Route 132",
        "Route 133",
        "Route 134",
        "Ever Grande City",
        "Victory Road",
        "S.S. Tidal",
        "Battle Frontier",
        "Artisan Cave",
    ],

    //--FireRed / LeafGreen--//
    [
        "Starter",
        "Pallet Town",
        "Route 1",
        "Viridian City",
        "Route 22",
        "Route 2",
        "Viridian Forest",
        "Route 3",
        "Route 4",
        "Mt. Moon",
        "Cerulean City",
        "Route 24",
        "Route 25",
        "Route 5",
        "Route 6",
        "Vermillion City",
        "Route 11",
        "Diglett's Cave",
        "Route 9",
        "Route 10",
        "Rock Tunnel",
        "Pokémon Tower",
        "Route 12",
        "Route 8",
        "Route 7",
        "Celadon City",
        "Route 16",
        "Route 17",
        "Route 18",
        "Fuschia City",
        "Safari Zone",
        "Route 15",
        "Route 14",
        "Route 13",
        "Power Plant",
        "Route 19",
        "Route 20",
        "Seafoam Islands",
        "Cinnabar Island",
        "Pokémon Mansion",
        "Route 21",
        "One Island",
        "Treasure Beach",
        "Kindle Road",
        "Mt. Ember",
        "Cape Brink",
        "Three Isle Port",
        "Bond Bridge",
        "Berry Forest",
        "Route 23",
        "Victory Road",
        "Four Island",
        "Icefall Cave",
        "Five Island",
        "Five Isle Meadow",
        "Memorial Pillar",
        "Water Labyrinth",
        "Resort Gorgeous",
        "Lost Cave",
        "Water Path",
        "Green Path",
        "Pattern Bush",
        "Outcast Island",
        "Altering Cave",
        "Ruin Valley",
        "Trainer Tower",
        "Canyon Entrance",
        "Seavault Canyon",
        "Tanoby Ruins",
        "Cerulean Cave",
    ],

    //--Diamond / Pearl / Platinum--//
    [
        "Starter",
        "Twinleaf Town",
        "Route 201",
        "Lake Verity",
        "Route 202",
        "Route 203",
        "Oreburgh Gate",
        "Oreburgh City",
        "Oreburgh Mine",
        "Route 207",
        "Route 204",
        "Ravaged Path",
        "Floaroma Meadow",
        "Route 205",
        "Valley Windworks",
        "Eterna Forest",
        "The Old Chateau",
        "Eterna City",
        "Route 206",
        "Wayward Cave",
        "Mt. Coronet",
        "Route 208",
        "Hearthome City",
        "Route 209",
        "The Lost Tower",
        "Solaceon Ruins",
        "Route 210",
        "Route 215",
        "Veilstone City",
        "Route 212",
        "Trophy Garden",
        "Pastoria City",
        "Great Marsh",
        "Route 213",
        "Valor Lakefront",
        "Lake Valor",
        "Route 214",
        "Ruin Maniac's Cave",
        "Ruin Maniac's Tunnel",
        "Celestic Town",
        "Fuego Ironworks",
        "Route 219",
        "Route 220",
        "Route 221",
        "Route 218",
        "Canalave City",
        "Iron Island",
        "Route 211",
        "Route 216",
        "Route 217",
        "Acuity Lakefront",
        "Lake Acuity",
        "Snowpoint Temple",
        "Route 222",
        "Sunyshore City",
        "Route 223",
        "Pokémon League",
        "Victory Road",
        "Route 224",
        "Route 230",
        "Route 229",
        "Resort Area",
        "Route 228",
        "Route 226",
        "Route 227",
        "Stark Mountain",
        "Route 225",
        "Sendoff Spring",
        "Turnback Cave",
        "Distortion World",
        "Spear Pillar",
        "Newmoon Island",
        "Flower Paradise",
        "Hall of Origin",
    ],

    //--HeartGold / SoulSilver--//
    [
        "Starter",
        "New Bark Town",
        "Route 29",
        "Cherrygrove City",
        "Route 30",
        "Route 31",
        "Dark Cave",
        "Violet City",
        "Sprout Tower",
        "Route 32",
        "Ruins of Alph",
        "Union Cave",
        "Route 33",
        "Azalea Town",
        "Slowpoke Well",
        "Ilex Forest",
        "Route 34",
        "Goldenrod City",
        "Route 35",
        "National Park",
        "Route 36",
        "Route 37",
        "Ecruteak City",
        "Burned Tower",
        "Bell Tower",
        "Route 38",
        "Route 39",
        "Olivine City",
        "Route 40",
        "Route 41",
        "Whirl Islands",
        "Cianwood City",
        "Cliff Edge Gate",
        "Route 47",
        "Cliff Cave",
        "Route 48",
        "Safari Zone Gate",
        "Safari Zone",
        "Route 42",
        "Mt. Mortar",
        "Mahogany Town",
        "Rocket Hideout",
        "Route 43",
        "Lake of Rage",
        "Route 44",
        "Ice Path",
        "Blackthorn City",
        "Dragon's Den",
        "Route 45",
        "Dark Cave 2",
        "Route 46",
        "Route 27",
        "Tohjo Falls",
        "Route 26",
        "Victory Road",
        "Indigo Plateau",
        "Vermillion City",
        "Route 6",
        "Saffron City",
        "Route 5",
        "Route 7",
        "Route 8",
        "Route 10",
        "Power Plant",
        "Rock Tunnel",
        "Route 9",
        "Cerulean City",
        "Route 24",
        "Route 25",
        "Route 4",
        "Route 16",
        "Route 17",
        "Route 18",
        "Fuschia City",
        "Route 15",
        "Route 14",
        "Route 13",
        "Route 12",
        "Route 11",
        "Diglett's Cave",
        "Route 2",
        "Pewter City",
        "Route 3",
        "Mt. Moon",
        "Viridian City",
        "Route 1",
        "Pallet Town",
        "Route 21",
        "Cinnabar Island",
        "Route 20",
        "Route 19",
        "Route 22",
        "Route 28",
        "Mt. Silver",
        "Cerulean Cave",
    ],
    //--Black / White--//
    [],

    //--Black 2 / White 2--//
    [
        "Starter",
        "Aspertia City",
        "Route 19",
        "Floccesy Town",
        "Route 20",
        "Floccesy Ranch",
        "Aspertia Gym",
        "Virbank City",
        "Virbank Complex",
        "Castelia City",
        "Castelia Sewers",
        "Relic Passage",
        "Route 4",
        "Desert Resort",
        "Relic Castle",
        "Route 16",
        "Lostlorn Forest",
        "Route 5",
        "Driftveil Drawbridge",
        "Driftveil City",
        "Route 6",
        "Mistralton Cave",
        "Chargestone Cave",
        "Route 7",
        "Celestial Tower",
        "Reversal Mountain",
        "Strange House",
        "Undella Town",
        "Undella Bay",
        "Route 13",
        "Route 12",
        "Village Bridge",
        "Route 11",
        "Route 9",
        "Seaside Cave",
        "Route 21",
        "Humilau City",
        "Route 22",
        "Giant Chasm",
        "Route 23",
        "Victory Road",
        "Old Victory Road",
        "Marvelous Bridge",
        "Route 15",
        "Route 14",
        "Abundant Shrine",
        "Moor of Icirrus",
        "Icirrus City",
        "Dragonspiral Tower",
        "Twist Mountain",
        "Clay Tunnel",
        "Underground Ruins",
        "Pinwheel Forest",
        "Nacrene City",
        "Route 3",
        "Wellspring Cave",
        "Striaton City",
        "Dreamyard",
        "Route 2",
        "Accumula Town",
        "Route 1",
        "Route 17",
        "Route 18",
        "P2 Laboratory",
        "Nature Preserve",
    ],

    //--X / Y--//
    [],

    //--OmegaRuby / AlphaSapphire--//
    [],

    //--Sun / Moon--//
    [],

    //--Ultra Sun / Ultra Moon--//
    [
        "Starter",
        "Hau'oli Outskirts",
        "Iki Town",
        "Route 1",
        "Melemele Sea",
        "Hau'oli City",
        "Route 2",
        "Berry Fields",
        "Verdant Cavern",
        "Hau'oli Cementery",
        "Route 3",
        "Melemele Meadow",
        "Seaward Cave",
        "Kala'e Bay",
        "Ten Carat Hill",
        "Hano Beach",
        "Route 4",
        "Paniola Town",
        "Paniola Ranch",
        "Route 5",
        "Brooklet Hill",
        "Route 6",
        "Route 7",
        "Wela Volcano Park",
        "Dividing Peak Tunnel",
        "Route 8",
        "Fossil Restoration",
        "Lush Jungle",
        "Diglett's Tunnel",
        "Route 9",
        "Konikoni City",
        "Memorial Hill",
        "Akala Outskirts",
        "Malie City",
        "Malie Garden",
        "Route 10",
        "Mount Hokulani",
        "Route 11",
        "Route 12",
        "Secluded Shore",
        "Blush Mountain",
        "Route 13",
        "Haina Desert",
        "Tapu Village",
        "Route 15",
        "Aether House",
        "Route 14",
        "Thrifty Megamart",
        "Route 16",
        "Ula'ula Meadow",
        "Lake of the Moone/Sunne",
        "Route 17",
        "Shady House",
        "Seafolk Village",
        "Poni Wilds",
        "Ancient Poni Path",
        "Poni Breaker Coast",
        "Exeggutor Island",
        "Vast Poni Canyon",
        "Altar of the Moone/Sunne",
        "Mount Lanakila",
        "Poni Grove",
        "Poni Plains",
        "Poni Meadow",
        "Resolution Cave",
        "Poni Coast",
        "Poni Gauntlet",
        "Ruins of Conflict",
        "Ruins of Life",
        "Ruins of Abundance",
        "Ruins of Hope",
    ],

    //--Sword and Shield--//
    [],
];

export default {
    names,
    routes,
};
